### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by MachineKillin** [drakelam/MLDChecker#1]
trying to open setup.exe it gives me the same error each time 
"Unable to locate application file 'SetupMLDChecker.msi'.

See the setup log file located at 'C:\Users\2aaa1\AppData\Local\Temp\VSDBA3E.tmp\install.log' for more information."
this is the log:
The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.7.2 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 528372
Setting value '528372 {int}' for property 'DotNetFull_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNetFull_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.7.2 (x86 and x64)':
Property: [DotNetFull_OSIntegrated] = 1 {int}
Property: [DotNetFull_Release] = 528372 {int}
Running checks for command 'DotNetFX472\NDP472-KB4054530-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX472\NDP472-KB4054530-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX472\NDP472-KB4054531-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThan' on property 'DotNetFull_Release' and value '461808': true
Result of checks for command 'DotNetFX472\NDP472-KB4054531-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.7.2 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
Error: Unable to locate application file 'SetupMLDChecker.msi'.

**Comment by drakelam** [comment]
Thank you for your message.
You can see if the required .NET Framework is fully installed.
You can see the information here:
https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/error-opening-installation-log-file
Or on this page to understand this installation error:
https://social.msdn.microsoft.com/Forums/windows/en-US/831f2dc7-85ac-494e-b6ba-1a2b20a9ccf2/setup-has-detected-that-the-file?forum=winformssetup
-------
Thank you for your interest!
